#!/bin/sh

flake8 --ignore E501,W503,E203 \
    bug-bind.py \
    lp-bug \
    mir-bug \
    oem-meta-packages \
    pkg-list \
    pkg-iot-meta \
    pkg-oem-meta \
    review-merge-proposal \
    setup.py \
    umadison
