#!/bin/sh

# shellcheck source=debian/tests/lp-online-guard
. "$(cd "$(dirname "$0")" && pwd)/lp-online-guard"
require_launchpad "$LAUNCHPAD_PRODUCTION"

# Public
lp-dl-attm 1
find lp1

# Private
lp-dl-attm 1923430
find lp1923430
