#!/bin/sh

cd "$AUTOPKGTEST_ARTIFACTS" || exit 1

export LAUNCHPAD_API="https://api.launchpad.net/"
RET=0

# list
oem-meta-packages --quiet list

# collect
oem-meta-packages --quiet collect oem-somerville-tentacool-meta -o /dev/null

oem-meta-packages --series jammy --quiet collect oem-somerville-tentacool-meta
if [ "$(jq -r '."oem-somerville-tentacool-meta".oem.git.kernel_meta' < oem-somerville-tentacool-meta.json)" != "linux-generic-hwe-22.04" ]; then
    echo "FAIL: 'oem-meta-packages --series jammy --quiet collect oem-somerville-tentacool-meta' failed."
    RET=1
fi

oem-meta-packages --series noble --quiet collect oem-somerville-treecko-meta
if [ "$(jq -r '."oem-somerville-treecko-meta".oem.git.kernel_meta' < oem-somerville-treecko-meta.json)" != "linux-generic-hwe-24.04" ]; then
    echo "FAIL: 'oem-meta-packages --series noble --quiet collect oem-somerville-treecko-meta' failed."
    RET=1
fi

oem-meta-packages --series jammy --quiet collect oem-stella-aron-meta
if [ "$(jq -r '."oem-stella-aron-meta".oem.devel.archive' < oem-stella-aron-meta.json)" != "cesg:stella-jammy-devel" ]; then
    echo "FAIL: 'oem-meta-packages --series jammy --quiet collect oem-stella-aron-meta' failed."
    RET=1
fi

oem-meta-packages --series noble --quiet collect oem-stella-yoshio-meta
if [ "$(jq -r '."oem-stella-yoshio-meta".oem.devel.archive' < oem-stella-yoshio-meta.json)" != "cesg:stella-noble-devel" ]; then
    echo "FAIL: 'oem-meta-packages --series noble --quiet collect oem-stella-yoshio-meta' failed."
    RET=1
fi

# create
cat > jellyfish-tentacool.json <<ENDLINE
{
  "biosids": [
    "0AF3"
  ],
  "certified": true,
  "metabug": 1968569,
  "mirbug": 1981784,
  "platform": "tentacool",
  "productnames": [
    "XPS 13 9320"
  ],
  "project": "somerville",
  "series": "jammy",
  "short_description": "XPS 13 9320",
  "kernel_meta": "linux-generic-hwe-22.04"
}
ENDLINE
oem-meta-packages create jellyfish-tentacool.json
mv oem-somerville-tentacool-meta jellyfish-tentacool-meta

cat > numbat-yoshio.json <<ENDLINE
{
  "biosids": [
    "8962"
  ],
  "certified": true,
  "kernel_meta": "linux-oem-24.04a",
  "metabug": "STELLA-1",
  "mirbug": 2089102,
  "platform": "yoshio",
  "productnames": [
    "HP Z4 G5 Workstation Desktop PC"
  ],
  "project": "stella",
  "series": "noble",
  "short_description": "HP Z4 G5 Workstation Desktop PC"
}
ENDLINE
oem-meta-packages create numbat-yoshio.json
mv oem-stella-yoshio-meta numbat-yoshio-meta

cat > jellyfish-cais.json <<ENDLINE
{
  "biosids": "M4G",
  "bvn": "LENOVO",
  "certified": true,
  "kernel_meta": "linux-oem-22.04a",
  "metabug": 1987085,
  "mirbug": 1997646,
  "platform": "cais",
  "productnames": [
    "ThinkStation P360 Tiny"
  ],
  "project": "sutton",
  "pvr": "ThinkStation",
  "series": "jammy",
  "short_description": "ThinkStation P360 Tiny"
}
ENDLINE
oem-meta-packages create jellyfish-cais.json
mv oem-sutton-cais-meta jellyfish-cais-meta-1

cat > jellyfish-cais.json <<ENDLINE
{
  "biosids": [
    "M4G",
    "M4H"
  ],
  "bvn": "LENOVO",
  "certified": true,
  "kernel_meta": "linux-oem-22.04a",
  "metabug": 1987085,
  "mirbug": 1997646,
  "platform": "cais",
  "productnames": [
    "ThinkStation P360 Tiny",
    "ThinkStation P360 Huge"
  ],
  "project": "sutton",
  "pvr": "ThinkStation",
  "series": "jammy",
  "short_description": "ThinkStation P360 Tiny/Huge"
}
ENDLINE
oem-meta-packages create jellyfish-cais.json
mv oem-sutton-cais-meta jellyfish-cais-meta-2

cat > numbat-treecko.json <<ENDLINE
{
  "auto_meta_creating": true,
  "biosids": [
    "0C87"
  ],
  "bvn": "DellInc.",
  "certification-hardware": [],
  "certified": false,
  "certify-planning": [
    2033464
  ],
  "hardware": [
    "202308-31925"
  ],
  "initial_biosidsfull": [
    [
      "0C87",
      "XPS 13 9340 (0C87)"
    ]
  ],
  "initial_productnames": [
    "XPS 13 9340 (0C87)"
  ],
  "kernel_meta": "linux-generic-hwe-24.04",
  "metabug": "casc-329",
  "mirbug": 2030831,
  "platform": "treecko",
  "pmbiosids": [
    "0C87"
  ],
  "project": "somerville",
  "pvr": "",
  "series": "noble",
  "short_description": "",
  "skus": [
    "TRBM-DVT1-C1"
  ]
}
ENDLINE
oem-meta-packages create numbat-treecko.json
rm -rf oem-somerville-treecko-meta

# update
oem-meta-packages --dry-run --series jammy update oem-somerville-tentacool-meta --kernel linux-generic-hwe-22.04
oem-meta-packages --dry-run --series jammy update oem-stella-aron-meta --kernel linux-generic-hwe-22.04
oem-meta-packages --dry-run --series noble update oem-somerville-treecko-meta --kernel linux-generic-hwe-22.04
oem-meta-packages --dry-run --series noble update oem-stella-yoshio-meta --kernel linux-generic-hwe-24.04

# staging-copy
oem-meta-packages --dry-run --series jammy staging-copy oem-somerville-tentacool-meta 2>&1 | grep -e cesg:somerville-jellyfish-tentacool-jammy-devel -e cesg:somerville-jellyfish-tentacool-jammy-staging
oem-meta-packages --dry-run --series jammy staging-copy oem-sutton-balesego-meta 2>&1 | grep -e cesg:sutton-jammy-devel -e cesg:sutton-jammy-staging

exit "$RET"
